# policy_path: "/home/niic/RL_control/Q1_control/src/q1_controller/policy/2025-10-31_21-45-24_Q1_251021_03_walk_120Hz_67500/policy.onnx"
policy_path: "src/q1_controller/policy/2025-10-31_21-45-24_Q1_251021_03_walk_120Hz_67500/policy.onnx"
# mocap_path: "/home/niic/RL_control/Q1_control/src/q1_controller/artifacts/Q1_251021_03_saw_120Hz_v3/motion.npz"
mocap_path: "src/q1_controller/artifacts/Q1_251021_03_saw_120Hz_v3/motion.npz"
# deploy_mode: "sim2real" # "sim2real","sim2sim"
deploy_mode: "sim2sim" # "sim2real","sim2sim"
num_actions: 29
num_single_obs: 154
frame_stack: 1
dt: 0.002
decimation: 10
action_scale: 0.25
recal_action_scale_by_tq_max_and_kp: true # new_scale = scale*torque_max/kp
action_limit: 10.0
gamepad_cmd_vel_scale_vx: 1.0
gamepad_cmd_vel_scale_vy: 1.0
gamepad_cmd_vel_scale_wz: 1.0

inputs:
  - name: "obs"
    shape: [1, 154]  # 示例：观测输入，维度根据 num_single_obs * frame_stack 计算
  - name: "time_step"
    shape: [1, 1]    # 示例：时间步输入

outputs:
  - name: "actions"
    shape: [1, 29]   # 示例：动作输出
  - name: "joint_pos"
    shape: [1, 29]   # 示例：其他输出（可选，根据模型实际配置）
  - name: "joint_vel"
    shape: [1, 29]
  - name: "body_pos_w"
    shape: [1, 15, 3]
  - name: "body_quat_w"
    shape: [1, 15, 4]
  - name: "body_lin_vel_w"
    shape: [1, 15, 3]
  - name: "body_ang_vel_w"
    shape: [1, 15, 3]

obs:
# obs中的内容清小心调整，注意先后的排序
- motion_joint_pos_command: { len: 29, scale: 1.0, slice: [ 0, 29 ] }
- motion_joint_vel_command: { len: 29, scale: 1.0, slice: [ 29, 58 ] }
- motion_ref_ori_b: { len: 6, scale: 1.0, slice: [ 58, 64 ] }
- base_ang_vel: { len: 3, scale: 1.0, slice: [ 64, 67 ] }
- joint_pos: { len: 29, scale: 1.0, slice: [ 67, 96 ] }
- joint_vel: { len: 29, scale: 1.0, slice: [ 96, 125 ] }
- last_actions: { len: 29, scale: 1.0, slice: [ 125, 154 ] }

ankle_pitch_add_angle: 0.2626 #rad
baselink_frame: "pelvis_link"
mimic_frame: "torso_link"

motors:
# 代码中的数据栈会根据下面关节出现的顺序进行构建,顺序默认为mujoco/isaacgym的深度搜索方式。
# 无论电机是否用得到，只要是在urdf中的转动关节，都必须写出来。
# 关节名称和ID一定要对上 ！！！！！！！！！！！！
# id表示的是在MotorInfo这个数据结构中的索引,从0到28
# ec_id表示MotorInfo中的id
# NOTE: ankle的两个关节的direction请务必是1
- L_hip_roll_joint:       { id: 14, ec_id: 109, direction:  1, kp: 180.0, kd: 2.5, torque_max:  90.0, default_pos: 0.0 }
- L_hip_yaw_joint:        { id: 15, ec_id: 110, direction: -1, kp: 180.0, kd: 2.5, torque_max:  60.0, default_pos: 0.0 }
- L_hip_pitch_joint:      { id: 16, ec_id: 111, direction: -1, kp: 330.0, kd: 3.0, torque_max: 330.0, default_pos: 0.0 }
- L_knee_joint:           { id: 17, ec_id: 112, direction:  1, kp: 330.0, kd: 3.0, torque_max: 330.0, default_pos: 0.0 }
- L_ankle_pitch_joint:    { id: 18, ec_id: 113, direction:  1, kp:  70.0, kd: 1.5, torque_max:  36.0, default_pos: 0.0 }
- L_ankle_roll_joint:     { id: 19, ec_id: 114, direction:  1, kp:  70.0, kd: 1.5, torque_max:  36.0, default_pos: 0.0 }

- R_hip_roll_joint:       { id: 20, ec_id: 209, direction:  1, kp: 180.0, kd: 2.5, torque_max:  90.0, default_pos: 0.0 }
- R_hip_yaw_joint:        { id: 21, ec_id: 210, direction: -1, kp: 180.0, kd: 2.5, torque_max:  60.0, default_pos: 0.0 }
- R_hip_pitch_joint:      { id: 22, ec_id: 211, direction:  1, kp: 330.0, kd: 3.0, torque_max: 330.0, default_pos: 0.0 }
- R_knee_joint:           { id: 23, ec_id: 212, direction: -1, kp: 330.0, kd: 3.0, torque_max: 330.0, default_pos: 0.0 }
- R_ankle_pitch_joint:    { id: 24, ec_id: 213, direction:  1, kp:  70.0, kd: 1.5, torque_max:  36.0, default_pos: 0.0 }
- R_ankle_roll_joint:     { id: 25, ec_id: 214, direction:  1, kp:  70.0, kd: 1.5, torque_max:  36.0, default_pos: 0.0 }

- pelvis_joint:           { id: 28, ec_id: 3  , direction:  1, kp: 140.0, kd: 1.5, torque_max:  42.0, default_pos: 0.0 }

- L_shoulder_pitch_joint: { id: 0 , ec_id: 101, direction:  1, kp:  70.0, kd: 1.5, torque_max:  42.0, default_pos: 0.0 }
- L_shoulder_roll_joint:  { id: 1 , ec_id: 102, direction: -1, kp:  70.0, kd: 1.5, torque_max:  42.0, default_pos: 0.0 }
- L_shoulder_yaw_joint:   { id: 2 , ec_id: 103, direction: -1, kp:  70.0, kd: 2.0, torque_max:  23.0, default_pos: 0.0 }
- L_elbow_joint:          { id: 3 , ec_id: 104, direction: -1, kp:  70.0, kd: 2.0, torque_max:  23.0, default_pos: 0.0 }
- L_forearm_yaw_joint:    { id: 4 , ec_id: 105, direction: -1, kp:  20.0, kd: 1.0, torque_max:   8.3, default_pos: 0.0 }
- L_wrist_roll_joint:     { id: 5 , ec_id: 106, direction: -1, kp:  20.0, kd: 1.0, torque_max:   3.3, default_pos: 0.0 }
- L_wrist_pitch_joint:    { id: 6 , ec_id: 107, direction:  1, kp:  20.0, kd: 1.0, torque_max:   3.3, default_pos: 0.0 }

- R_shoulder_pitch_joint: { id: 7 , ec_id: 201, direction: -1, kp:  70.0, kd: 1.5, torque_max:  42.0, default_pos: 0.0 }
- R_shoulder_roll_joint:  { id: 8 , ec_id: 202, direction: -1, kp:  70.0, kd: 1.5, torque_max:  42.0, default_pos: 0.0 }
- R_shoulder_yaw_joint:   { id: 9 , ec_id: 203, direction: -1, kp:  70.0, kd: 2.0, torque_max:  23.0, default_pos: 0.0 }
- R_elbow_joint:          { id: 10, ec_id: 204, direction:  1, kp:  70.0, kd: 2.0, torque_max:  23.0, default_pos: 0.0 }
- R_forearm_yaw_joint:    { id: 11, ec_id: 205, direction: -1, kp:  20.0, kd: 1.0, torque_max:   8.3, default_pos: 0.0 }
- R_wrist_roll_joint:     { id: 12, ec_id: 206, direction: -1, kp:  20.0, kd: 1.0, torque_max:   3.3, default_pos: 0.0 }
- R_wrist_pitch_joint:    { id: 13, ec_id: 207, direction: -1, kp:  20.0, kd: 1.0, torque_max:   3.3, default_pos: 0.0 }

- head_yaw_joint:         { id: 26, ec_id:   1, direction:  1, kp:   3.0, kd: 0.6, torque_max:  2.52, default_pos: 0.0 }
- head_pitch_joint:       { id: 27, ec_id:   2, direction:  1, kp:   1.5, kd: 0.3, torque_max:  1.26, default_pos: 0.0 }

joint_index_in_need: [ 
  "L_hip_roll_joint", "L_hip_yaw_joint", "L_hip_pitch_joint", "L_knee_joint", "L_ankle_pitch_joint", "L_ankle_roll_joint", 
  "R_hip_roll_joint", "R_hip_yaw_joint", "R_hip_pitch_joint", "R_knee_joint", "R_ankle_pitch_joint", "R_ankle_roll_joint", 
  "pelvis_joint", 
  "L_shoulder_pitch_joint", "L_shoulder_roll_joint", "L_shoulder_yaw_joint", "L_elbow_joint", "L_forearm_yaw_joint", "L_wrist_roll_joint", "L_wrist_pitch_joint", 
  "R_shoulder_pitch_joint", "R_shoulder_roll_joint", "R_shoulder_yaw_joint", "R_elbow_joint", "R_forearm_yaw_joint", "R_wrist_roll_joint", "R_wrist_pitch_joint", 
  "head_yaw_joint", "head_pitch_joint" 
  ] #motors中申明的电机不一定在推理相关的过程中被使用,joint_index_in_need这个索引是基于gym/mujoco的顺序,将决定哪些电机参与推理

isaac_sim_trans_flag: true # true , flase
motion_body_index: [ 0, 4, 14, 22, 5, 15, 23, 3, 11, 20, 28, 12, 21, 29, 13 ] # hpx的mimic需要
isaac_sim2mujoco_index: [ 0, 3, 8, 13, 17, 21, 1, 4, 9, 14, 18, 22, 2, 5, 10, 15, 19, 23, 25, 27, 6, 11, 16, 20, 24, 26, 28, 7, 12 ]
mujoco2isaac_sim_index: [ 0, 6, 12, 1, 7, 13, 20, 27, 2, 8, 14, 21, 28, 3, 9, 15, 22, 4, 10, 16, 23, 5, 11, 17, 24, 18, 25, 19, 26 ]
